/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:dbba4e03-bbb0-48dc-adbc-e8b259395c49",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_KIM6sgOgy",
    "aws_user_pools_web_client_id": "4d1g2mjik8sq2v9g3mjm44tacn",
    "oauth": {},
    "aws_user_files_s3_bucket": "naturesocietyd770eeed1aeb4e34ba859038a344c121174124-prod",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
